### ISSUE TITLE
Migrate to the new Scala Evaluator build

### ISSUE THREAD

**Issue by noelmarkham** [scala-exercises/evaluator#41]
This issue/document is intended to be a plan for migrating the current Scala Evaluator to one using Docker.

The current Scala Evaluator is at http://scala-evaluator.herokuapp.com.
The new Scala Evaluator is at http://scala-evaluator-sandbox.herokuapp.com.

### Motivation
A new Scala Evaluator has been deployed in a Docker container to provide greater protection for running third-party code. This has been deployed in parallel so as to keep continuity with applications already running the evaluator while we switch to the new one.

For most applications, migrating to the new Evaluator is simply an endpoint change in configuration, and an update to the auth token header used in requests.

### Plan outline

In a nutshell:
  * Move applications to the new endpoint
  * Confirm they still work
  * Update original endpoint to the new build
  * Move the applications back to the original endpoint
  * Confirm they still work
  * Remove the unused endpoint completely

Tasks:
- [x] Confirm Kazari works against the new endpoint
- [x] Update and redeploy sbot to the new endpoint
- [x] Update the new endpoint to use professional Heroku dynos
- [x] Update and redeploy Scala Exercises to the new endpoint
- [x] Configure builds to deploy Docker builds to the original endpoint
- [x] Confirm Kazari works against the original endpoint
- [x] Update and redeploy sbot to the original endpoint
- [x] Update and redeploy Scala Exercises to the original endpoint
- [x] Delete scala-evaluator-sandbox Heroku app

While this seems like more steps than necessary, performing the steps this way (that is, update config to the new endpoint, start deploying Docker builds to the original endpoint, update config back to the original endpoint) allows for continuity during the releases, and a more stable approach and easier rollback should anything go wrong.

**Comment by raulraja** [comment]
This looks like a great plan to me.

**Comment by noelmarkham** [comment]
Migration completed, sandbox app deleted, and Kazari, Sbot and Scala Exercises are all happy.
