### ISSUE TITLE
Deploy evaluator for Scala 2.12 and provision deployment for 2.11 and 212

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/evaluator#47]
@juanpedromoreno  and I have spent some time evaluating the option of running code that is supposed to be compiled and executed with Scala 2.11 and 2.12 and finally after fighting with classloaders and having it mostly working we decided to not continue down that path. The issue boils down to classes loaded with a version of Scala fail at runtime if sent to a classloader that is loading another version of Scala because of bin compat issues among the runtime and compilers being on a different version. Furthermore the code to make this work is way too dynamic and harder to maintain than having a code base cross-compiling.

We have finally decided to have two separate endpoints one where code targeting 2.12 is evaluated and another for 2.11. We need to keep the current evaluator server as is until we have scala exercises migrated but we need to deploy the app in a new Heroku App the same way you did for the current evaluator but that targets 2.12 instead of Scala 2.11.

We already have a branch ready https://github.com/scala-exercises/evaluator/tree/evaluator-free-of-classpath-issues which cross compiles to 2.11 and 2.12, so presumably we just need to modify the docker stuff to load the proper jar and classpath on each server based on which Scala Version we are deploying in that server.

**Comment by noelmarkham** [comment]
This has been deployed to a new Heroku endpoint, scala-evaluator-212.herokuapp.com, @juanpedromoreno is happy. Closing the ticket.
